package: cntndTemplate
version: '0.0.1'
author: 'Thomas D Ascoli'
info: 'Add On zum editieren der CSS/JS Dateien des Templates'

page:
  title: 'translate:title'

installer_ignore:
  - xampp.bat
  - gulpfile.js
  - package.json
  - package-lock.json
  - .github
  - node_modules
  - addon
