package: cntndTemplate
version: '0.0.1'
author: 'Thomas D Ascoli'
info: 'Add On zum editieren der CSS/JS Dateien des Templates'

page:
  title: 'translate:title'
  icon: rex-icon fa-box
  subpages:
    css: {title: 'translate:css'}
    js: {title: 'translate:js'}

requires:
  packages:
    aceeditor: '^1.2.1'

installer_ignore:
  - xampp.bat
  - gulpfile.js
  - package.json
  - package-lock.json
  - .github
  - node_modules
  - addon
